# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - infrastructure
    - azure-infrastructure-pipelines.yml

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Provision'

  variables:
    - group: terraform-arm
    
  jobs:
  - job: 'Terraform'

    steps:
    - bash: terraform init
      displayName: 'Terraform init'
      workingDirectory: infrastructure
      env:
        ARM_SUBSCRIPTION_ID:  $(arm-subscription-id)
        ARM_CLIENT_ID:        $(arm-client-id)
        ARM_CLIENT_SECRET:    $(arm-client-secret)
        ARM_TENANT_ID:        $(arm-tenant-id)
        TF_VAR_test_admin_pw: P@ssword!

    - bash: terraform plan -out provision.plan
      displayName: 'Terraform plan'
      workingDirectory: infrastructure
      env:
        ARM_SUBSCRIPTION_ID:  $(arm-subscription-id)
        ARM_CLIENT_ID:        $(arm-client-id)
        ARM_CLIENT_SECRET:    $(arm-client-secret)
        ARM_TENANT_ID:        $(arm-tenant-id)
        TF_VAR_test_admin_pw: P@ssword!

