# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - infrastructure
    - azure-infrastructure-pipelines.yml

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Provision'

  jobs:
  - job: 'Terraform'

    steps:
    - bash: terraform init
      displayName: 'Terraform init'
      workingDirectory: infrastructure

    - bash: terraform plan -out provision.plan
      displayName: 'Terraform plan'
      workingDirectory: infrastructure
